### ISSUE TITLE
Upload from mobile.php not found

### ISSUE THREAD

**Issue by ghost** [nusofthq/Pipe-iOS-SDK#1]
Not ble to upload video 
-(void) videoUploadSuccess:(PipeDelegate *)sender withResult:(NSString *)result{
    NSLog(@"Video result = %@", result);
**It returns HTML response in _result_**
}

**Comment by octavn** [comment]
We've made some important changes to our infrastructure recently. Those changes have lead to this error. The iOS SDK will be updated soon to correctly map to those changes.

**Comment by octavn** [comment]
The iOS SDK has now been updated with the correct path to our new infrastructure.
